name: linkcheck

on:
  # Run once per day
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      # Checkout and setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install and build
      - name: Install
        run: npm ci
      # Run linkcheck, propagate linkcheck failure through grep pipe
      - name: Linkcheck
        run: set -o pipefail; npm run linkcheck 2>/dev/null | grep "Getting links from\|BROKEN"
