name: linkcheck

on:
  # Run once per day
  schedule:
    - cron: '21 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install and build
      - name: Install
        run: npm ci
      # Run linkcheck, propagate linkcheck failure through grep pipe
      - name: Linkcheck
        run: set -o pipefail; npm run linkcheck:prod 2>/dev/null | grep "Getting links from\|BROKEN"
